name: Build & Publish APT repo

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Debian packaging tools
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev reprepro gnupg

      - name: Build .deb
        run: |
          cd packaging
          chmod +x pack.sh
          ./pack.sh

      - name: Verify package contains /etc/profile.d wrapper
        run: |
          set -euo pipefail
          # find the produced .deb
          deb=$(ls packaging/infoprompt_*_all.deb | head -n1)
          echo "Checking $deb for /etc/profile.d/infoprompt.sh"
          dpkg-deb -c "$deb" | awk '{print $6}' | grep -q '^/etc/profile.d/infoprompt.sh$' || (dpkg-deb -c "$deb" && echo 'Wrapper not found in package' && exit 1)

      - name: Create repo and include package
        run: |
          mkdir -p repo/conf repo/pool
          printf '%s\n' \
            'Origin: infoprompt' \
            'Label: infoprompt' \
            'Codename: stable' \
            'Architectures: all' \
            'Components: main' \
            'SignWith: false' \
            > repo/conf/distributions
          # Put the .deb into the pool and generate Packages/Packages.gz and Release
          mkdir -p repo/pool/main/i/infoprompt
          # copy the .deb produced by packaging/pack.sh into the pool
          cp packaging/infoprompt_*_all.deb repo/pool/main/i/infoprompt/
          # Generate Packages file and gzip it
          mkdir -p repo/dists/stable/main/binary-all
          dpkg-scanpackages repo/pool /dev/null > repo/dists/stable/main/binary-all/Packages
          gzip -9 -c repo/dists/stable/main/binary-all/Packages > repo/dists/stable/main/binary-all/Packages.gz
          # Create Release file with checksum for the Packages.gz
          printf '%s\n' \
            'Origin: infoprompt' \
            'Label: infoprompt' \
            'Suite: stable' \
            'Codename: stable' \
            'Architectures: all' \
            'Components: main' \
            'Description: infoprompt apt repository' \
            > repo/dists/stable/Release
          sha256=$(sha256sum repo/dists/stable/main/binary-all/Packages.gz | cut -d' ' -f1)
          printf 'SHA256: %s %s\n' "$sha256" "repo/dists/stable/main/binary-all/Packages.gz" >> repo/dists/stable/Release

      - name: Import GPG key and sign Release
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${GPG_PRIVATE_KEY:-}" ]; then
            echo "No GPG_PRIVATE_KEY provided; skipping signing"
            exit 0
          fi
          # Import private key
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          # Extract primary key ID (long keyid/fingerprint) from secret keys
          GPG_KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/ {print $5; exit}')
          echo "Using GPG key ID: $GPG_KEY_ID"
          # Export public key for users
          gpg --armor --export "$GPG_KEY_ID" > repo/infoprompt.gpg
          # Create signed InRelease (clear-signed) and detached Release.gpg (if Release exists)
          if [ -f repo/dists/stable/Release ]; then
            gpg --batch --yes --default-key "$GPG_KEY_ID" --clearsign -o repo/dists/stable/InRelease repo/dists/stable/Release || true
            gpg --batch --yes --default-key "$GPG_KEY_ID" --detach-sign -a -o repo/dists/stable/Release.gpg repo/dists/stable/Release || true
          fi

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
